AllCops:
  TargetRubyVersion: 3.2

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - cn
    - uid

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'
